apiVersion: v1
kind: Service
metadata:
  name: wp-svc

spec:
  selector:
    app: wordpress
    type: fronttier
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080